basePath: /
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  license:
    name: none
  termsOfService: localhost:8080
  title: インスタグラムもどき課題 API サーバー
  version: 1.0.0
paths:
  /auth:
    get:
      consumes:
      - application/json
      description: sessionとcookieの値を比較し、ログイン状態を判定
      operationId: authUserLogin
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: ユーザーのログイン状態を判定
swagger: "2.0"
tags:
- name: go-instagram
